### ISSUE TITLE
Support data property for OpenURL and ShowCard Actions

### ISSUE THREAD

**Issue by colbytimmsl** [MicrosoftDocs/AdaptiveCards#186]
In the current implementation of Adaptive Cards, only the submit action supports the data property. It would be great to add support for this property to the other actions: openurl and showcard.

**Comment by andrewleader** [comment]
Hi @colbytimmsl, how exactly would you use `data` on `Action.ShowCard` and `Action.OpenUrl`? ShowCard doesn't send anything, it purely shows another card, so I'm struggling to see how that'd be useful. `Action.OpenUrl` simply opens a web browser (via a URL), how would you use `data` there?

Closing this issue since it's not a docs issue, but we can keep discussing here :)
